# Generated by Django 5.1.3 on 2026-08-29 09:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('author', models.CharField(max_length=255, verbose_name='Muallif')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('sale', 'Sotish'), ('rent', 'Ijara'), ('barter', 'Barter')], max_length=10, verbose_name='Holat')),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('like_new', 'Yangidek'), ('good', 'Yaxshi'), ('acceptable', 'Qoniqarli')], default='good', max_length=15, verbose_name='Holat')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Narx (so'm)")),
                ('barter_wish', models.CharField(blank=True, max_length=500, verbose_name='Barter sharti')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-is_premium', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Emoji ikonka')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Shahar nomi')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Rasm')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book')),
            ],
            options={
                'verbose_name': 'Kitob rasmi',
                'verbose_name_plural': 'Kitob rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category', verbose_name='Kategoriya'),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='books.book')),
            ],
            options={
                'verbose_name': 'Suhbat xonasi',
                'verbose_name_plural': 'Suhbat xonalari',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.city', verbose_name='Shahar'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tuman nomi')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='books.city', verbose_name='Shahar')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['name'],
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.district', verbose_name='Tuman'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name="To'liq ism")),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.city', verbose_name='Shahar')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.district', verbose_name='Tuman')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='bookzone_users', related_query_name='bookzone_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='bookzone_users', related_query_name='bookzone_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='books.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='books.user')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user1', to='books.user'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user2', to='books.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.user', verbose_name='Egasi'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='books.user')),
            ],
            options={
                'verbose_name': 'Sevimli',
                'verbose_name_plural': 'Sevimlilar',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('book', 'user1', 'user2')},
        ),
    ]
