# Generated by Django 5.1.3 on 2026-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.TextField(verbose_name='Rasm (base64)'),
        ),
    ]
